# Generated by Django 3.0.3 on 2020-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200226_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='picture',
            field=models.ImageField(default='poll/default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='poll_choice',
            name='image',
            field=models.ImageField(default='poll_choice/default.jpg', upload_to=''),
        ),
    ]
