# Generated by Django 3.0.2 on 2020-02-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200226_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(default='poll/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='image',
            field=models.ImageField(default='poll/default_choice.jpg', upload_to=''),
        ),
    ]
