# Generated by Django 3.0.2 on 2020-02-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200227_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(default='poll/default.png', upload_to='poll/'),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='image',
            field=models.ImageField(default='poll/default_choice.jpg', upload_to='choice/'),
        ),
    ]
