# Generated by Django 3.0.3 on 2020-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200227_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_choice',
            name='image',
            field=models.ImageField(default='choice/default_choice.jpg', upload_to='choice/'),
        ),
    ]
