# Generated by Django 3.0.2 on 2020-03-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200228_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(blank=True, default='poll/default.png', upload_to='poll/'),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='image',
            field=models.ImageField(blank=True, default='choice/default.png', upload_to='choice/'),
        ),
    ]
