# Generated by Django 3.0.2 on 2020-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200302_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(default='poll/default.png', upload_to='poll/'),
        ),
    ]
