# Generated by Django 3.0.3 on 2020-03-04 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200304_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
