# Generated by Django 3.0.3 on 2020-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200306_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
