# Generated by Django 3.0.3 on 2020-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200310_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
