# Generated by Django 3.0.3 on 2020-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20200310_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(default='poll/poll_default.png', upload_to='poll/'),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='image',
            field=models.ImageField(default='choice/choice_default.png', upload_to='choice/'),
        ),
    ]
