# Generated by Django 3.0.3 on 2020-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20200311_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(default='poll/poll_default.gif', upload_to='poll/'),
        ),
    ]
