# Generated by Django 3.0.2 on 2020-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200311_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
